### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by Ironholds** [bnoordhuis/punycode#1]
Not really an issue, more a request for assistance; so I'm hoping to integrate this lib with a C++ lib I've written. Got any pointers on how one would pass the results of the decoding/encoding process into a C++ string (and, vice-versa, how one would pass a C++ string in)? This kind of integer-based value manipulation is new to me.

**Comment by romainfrancois** [comment]
Hi @Ironholds, I'm starting to wrap up an R 📦 [here](https://github.com/romainfrancois/puny). Most of the magic was borrowed from stringi.

**Comment by Ironholds** [comment]
@romainfrancois ahh! Er; there is, fwiw, now a punycode encoder and decoder in urltools ;)

**Comment by romainfrancois** [comment]
I should have checked that. Perhaps if i had seen your question before wrapping this c library 🤷‍♂️. 

On the + side, now i guess you can ❌ this issue.

**Comment by Ironholds** [comment]
Hey, too many good tools is never the problem :D
